# Generated by Django 4.1.2 on 2022-10-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True, 'verbose_name': 'contact', 'verbose_name_plural': 'contact'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
