# Generated by Django 4.1.2 on 2022-10-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bag',
            new_name='bags',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cloth',
            new_name='cloths',
        ),
    ]
