# Generated by Django 4.1.2 on 2022-10-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_bag_product_bags_rename_cloth_product_cloths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cloths',
        ),
        migrations.AddField(
            model_name='product',
            name='bag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cloth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='perfume',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoes',
            field=models.BooleanField(default=False),
        ),
    ]
